#region Using ...
using System.Collections.Generic;
using System.Threading.Tasks;
using HotelReservationService.Core.Models.ViewModels;
#endregion

/*
* Generated by: CodeGenerator Version 1.0.0.0
* Generated for: SmarttechSys
*/
namespace HotelReservationService.Core.IServices
{
    /// <summary>
    /// 
    /// </summary>
    public interface IUsersService
    {
        #region Methods
        Task ValidateModelAsync(UserViewModel model);

        Task<UserViewModel> AddAsync(UserViewModel model);

        UserLoggedInViewModel Login(LoginViewModel model);
        #endregion
    }
}
